# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080


# Spring配置
spring:
  profiles:
    active: dev
  application:
    name: myapp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.19.177:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: my-secret-pw
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 124.221.19.177
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.start.app.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    cache-enabled: false
    lazy-loading-enabled: false
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: PARTIAL
    default-executor-type: SIMPLE
    safe-row-bounds-enabled: false
    local-cache-scope: SESSION
    jdbc-type-for-null: OTHER
    call-setters-on-nulls: true


# Swagger配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API docs


# 钉钉机器人配置
dingtalk:
  robot:
    webhook-url: https://oapi.dingtalk.com/robot/send?access_token=66ee36d70ab36d9f124e0329a0987786c16e2fe2618eeaa968f373cf9191c7ab
    secret: SECa083f7bde05dc44365be2243e21f46808ac2d4ea5f00b7a3dbbd5ed712595a2c

# 日志配置
logging:
  level:
    root: INFO
    org.start.app: DEBUG
    org.start.app.filter: INFO
  file:
    name: ./logs/myapp.log

